// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYQ9vIv1L_-_FtyDNdz9K_yKImGO7k6SY',
    appId: '1:598850982161:web:da68e396ffe407753b7cb0',
    messagingSenderId: '598850982161',
    projectId: 'rishi-ecommerce-app',
    authDomain: 'rishi-ecommerce-app.firebaseapp.com',
    storageBucket: 'rishi-ecommerce-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3oTKE8WpjHSI0QlirHwd4bhbV553NRKg',
    appId: '1:598850982161:android:b5d38d7c5c5d5a543b7cb0',
    messagingSenderId: '598850982161',
    projectId: 'rishi-ecommerce-app',
    storageBucket: 'rishi-ecommerce-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWKJ1-WnZEYIuzN-GrwPwnsPeLPwU5jts',
    appId: '1:598850982161:ios:641cc65e8f0b18063b7cb0',
    messagingSenderId: '598850982161',
    projectId: 'rishi-ecommerce-app',
    storageBucket: 'rishi-ecommerce-app.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWKJ1-WnZEYIuzN-GrwPwnsPeLPwU5jts',
    appId: '1:598850982161:ios:641cc65e8f0b18063b7cb0',
    messagingSenderId: '598850982161',
    projectId: 'rishi-ecommerce-app',
    storageBucket: 'rishi-ecommerce-app.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYQ9vIv1L_-_FtyDNdz9K_yKImGO7k6SY',
    appId: '1:598850982161:web:ee2809c6fd1d3fdc3b7cb0',
    messagingSenderId: '598850982161',
    projectId: 'rishi-ecommerce-app',
    authDomain: 'rishi-ecommerce-app.firebaseapp.com',
    storageBucket: 'rishi-ecommerce-app.firebasestorage.app',
  );
}
